//************ sym.h **************
#define symSYMMAX         35
#define symEOF             0
#define symerror           1
#define symIDENTIFIER      2
#define symNUMBER          3
#define symPLUS            4
#define symMINUS           5
#define symMUL             6
#define symDIV             7
#define symEQ              8
#define symNEQ             9
#define symLESS           10
#define symLEQ            11
#define symGREATER        12
#define symGEQ            13
#define symLPAREN         14
#define symRPAREN         15
#define symCOMMA          16
#define symSEMI           17
#define symPERIOD         18
#define symBECOMES        19
#define symBEGIN          20
#define symEND            21
#define symIF             22
#define symTHEN           23
#define symWHILE          24
#define symDO             25
#define symREAD           26
#define symWRITE          27
#define symIDENTIFIERLIST 28
#define symCALL           29
#define symCONST          30
#define symVAR            31
#define symPROCEDURE      32
#define symPROGRAM        33
#define symSTRING         34
